{
  lib,
  config,
  pkgs,
  ...
}:

{
  options = {
    myModules.waybar.enable = lib.mkEnableOption "Waybar";
  };

  config = lib.mkIf config.myModules.waybar.enable {
    programs.waybar = {
      enable = true;
      package = pkgs.waybar;
      settings = import ./config.nix;
      style =
        # Load colour variables from the active theme at runtime.
        # This path is a symlink managed by nix-theme-set, pointing to
        # ~/.config/themes/<name>/waybar.css — generated by targets/waybar-colours.nix.
        # @import must come first so variables are defined before style.nix uses them.
        ''
          @import "${config.home.homeDirectory}/.local/state/theme/current/waybar.css";
        ''
        # Structural CSS — layout, sizing, border-radius etc.
        # References colour variables defined by the @import above.
        + (import ./style.nix);
    };
  };
}
